[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mr_heygen"
version = "1.0.0"
description = "HeyGen interactive video avatar"
requires-python = ">=3.7"
dependencies = []
